version: "3.8"

services:
  web:
    image: rahulnumo/devops-portfolio:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./certs/selfsigned.key:/etc/ssl/private/selfsigned.key:ro
